import type { Metadata } from "next";
import "../globals.css";
import TopNavigation from '@/components/sections/TopNavigation';
import Footer from '@/components/sections/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-gray-50">
        <TopNavigation />
        <div className="flex-grow">
          {children}

        </div>
        <Footer />
      </body>
    </html>
  );
}